### ISSUE TITLE
Databases for all the state and LGA, hospitals (govt/private), police station in Nigeria.

### ISSUE THREAD

**Issue by happyjosh-tech** [BuildForSDG/Team-102-GoodHealthAndWellBeing#5]
State and local govt
Hospitals: names, address, email, phone number/ mortuary
Police station: divisions, address, email, phone number.
Hotels; names, address, email, phone number.
These database can be created if there are no existing or availability API.

**Comment by Akaypee** [comment]
![FireShot Capture 086 - Change FRSC - Django site admin - 127 0 0 1](https://user-images.githubusercontent.com/48234870/84332977-521fbb00-ab86-11ea-90ef-0bb371b2a88f.png)
![FireShot Capture 087 - Change Hospital - Django site admin - 127 0 0 1](https://user-images.githubusercontent.com/48234870/84332988-5a77f600-ab86-11ea-886f-9a3111be9a7e.png)
![FireShot Capture 088 - Change Hotel - Django site admin - 127 0 0 1](https://user-images.githubusercontent.com/48234870/84332998-5f3caa00-ab86-11ea-9468-fb2c841859e8.png)
![FireShot Capture 089 - Change PoliceStation - Django site admin - 127 0 0 1](https://user-images.githubusercontent.com/48234870/84333008-64015e00-ab86-11ea-9f6f-ad05f355b1e3.png)
